version: '3.8'

services:
  # Modern Web Backend (FastAPI)
  web-backend:
    build:
      context: ./web_frontend/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - CO_API_KEY=${CO_API_KEY}
      - PYTHONPATH=/app
    volumes:
      - ./local_dump:/app/local_dump
      - ./domain_dict:/app/domain_dict
      - ./configs:/app/configs
      - ./web_frontend/backend/uploads:/app/uploads
      - ./web_frontend/backend/results:/app/results
    depends_on:
      - redis
    networks:
      - vidove-network
    restart: unless-stopped

  # Modern Web Frontend (React)
  web-frontend:
    build:
      context: ./web_frontend/frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      - web-backend
    networks:
      - vidove-network
    restart: unless-stopped

  # Redis for caching and task queues
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vidove-network
    restart: unless-stopped

  # Nginx reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web-frontend
      - web-backend
    networks:
      - vidove-network
    restart: unless-stopped
    profiles:
      - production

networks:
  vidove-network:
    driver: bridge

volumes:
  redis_data:
  uploads:
  results:
  local_dump:
