# -*- coding: utf-8 -*-
# The functions are adapted from project N46Whisper.
# https://github.com/Ayanaminn/N46Whisper
# Only the 'default' subtitle style used by the ViDove pipeline is kept.

import os
import regex as re
import codecs


def fileopen(input_file):
    # use correct codec to encode the input file
    encodings = ["utf-32", "utf-16", "utf-8", "cp1252", "gb2312", "gbk", "big5"]
    srt_src = ''
    for enc in encodings:
        try:
            with codecs.open(input_file, mode="r", encoding=enc) as fd:
                srt_src = fd.read()
                break
        except Exception:
            # print enc + ' failed'
            continue
    return [srt_src, enc]


def srt2ass(input_file, sub_style, is_split, split_method):
    if '.ass' in input_file:
        return input_file

    if not os.path.isfile(input_file):
        print(input_file + ' not exist')
        return

    src = fileopen(input_file)
    srt_content = src[0]
    # encoding = src[1] # Will not encode so do not need to pass codec para
    src = ''
    utf8bom = ''

    if u'\ufeff' in srt_content:
        srt_content = srt_content.replace(u'\ufeff', '')
        utf8bom = u'\ufeff'

    srt_content = srt_content.replace("\r", "")
    lines = [x.strip() for x in srt_content.split("\n") if x.strip()]
    subLines = ''
    dlgLines = ''  # dialogue line
    lineCount = 0
    output_file = '.'.join(input_file.split('.')[:-1])
    output_file += '.ass'

    for ln in range(len(lines)):
        line = lines[ln]
        if (
            line.isdigit()
            and ln + 1 < len(lines)
            and re.match(r'-?\d{1,2}:\d\d:\d\d', lines[ln + 1])
        ):
            if dlgLines:
                subLines += dlgLines + "\n"
            dlgLines = ''
            lineCount = 0
            continue
        else:
            if re.match(r'-?\d{1,2}:\d\d:\d\d', line):
                line = line.replace('-0', '0')
                dlgLines += 'Dialogue: 0,' + line + ',default,,0,0,0,,'
            else:
                if lineCount < 2:
                    dlg_string = line
                    if is_split == "Yes" and split_method == 'Modest':
                        # do not split if space proceed and followed by non-ASC-II characters
                        # do not split if space followed by word that less than 5 characters
                        split_string = re.sub(r'(?<=[^\x00-\x7F])\s+(?=[^\x00-\x7F])(?=\w{5})', r'|', dlg_string)
                        if len(split_string.split('|')) > 1:
                            dlgLines += (split_string.replace('|', "(adjust_required)\n" + dlgLines)) + "(adjust_required)"
                        else:
                            dlgLines += line
                    elif is_split == "Yes" and split_method == 'Aggressive':
                        # do not split if space proceed and followed by non-ASC-II characters
                        # split at all the rest spaces
                        split_string = re.sub(r'(?<=[^\x00-\x7F])\s+(?=[^\x00-\x7F])', r'|', dlg_string)
                        if len(split_string.split('|')) > 1:
                            dlgLines += (split_string.replace('|', "(adjust_required)\n" + dlgLines)) + "(adjust_required)"
                        else:
                            dlgLines += line
                    else:
                        dlgLines += line
                else:
                    dlgLines += "\n" + line
            lineCount += 1

    subLines += dlgLines + "\n"

    # ASS uses H:MM:SS.cc — keep one hour digit, convert ms to centiseconds
    subLines = re.sub(r'\d*(\d:\d{2}:\d{2}),(\d{2})\d', '\\1.\\2', subLines)
    subLines = re.sub(r'\s+-->\s+', ',', subLines)

    head_str = STYLE_DICT.get('head_str_default')
    output_str = utf8bom + head_str + '\n' + subLines
    # encode again for head string
    output_str = output_str.encode('utf8')

    with open(output_file, 'wb') as output:
        output.write(output_str)

    output_file = output_file.replace('\\', '\\\\')
    output_file = output_file.replace('/', '//')
    return output_file


STYLE_DICT = {
    'head_str_default': '''[Script Info]
; This is an Advanced Sub Station Alpha v4+ script.
; The script is generated by N46Whisper
Title:
ScriptType: v4.00+
Collisions: Normal
PlayDepth: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: default,Source Han Sans CN,90,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00050506,-1,0,0,0,100,100,5,0,1,3.5,0,2,135,135,10,1
[Events]
Format: Layer, Start, End, Style, Actor, MarginL, MarginR, MarginV, Effect, Text''',
}
