# configuration for each task
source_lang: EN
target_lang: ZH
domain: General

# YouTube Download Option
video_download:
  resolution: 480 # 360, 480, 720, best(best we can find)

MEMEORY: 
  enable_local_knowledge: True
  enable_vision_knowledge: True
  enable_web_search: True
  local_knowledge_path: "/Users/liujiaen/Documents/Codes/ViDove/domain_dict"

# VAD config
VAD:
  VAD_model: "pyannote/speaker-diarization-3.1"

# ASR config
ASR:
  ASR_model: openai/whisper-large-v3 # openai/whisper-large-v3, stable-whisper-base, stable-whisper-medium, stable-whisper-large, whisper-api

vision:
  enable_vision: True
  vision_model: gpt-4o # clip or other vLLMs
  model_path: ./ViDove/vision_model/clip-vit-base-patch16 # replace it with your own model path
  frame_cache_dir: ./cache #should be cleared after task finished
  frame_per_seg: 4 # number of frame extracted from segment
  
# pre-process module config
pre_process: 
  sentence_form: True
  spell_check: False
  term_correct: True

# Translation module config
translation:
  model: gpt-4o # choices=["gpt-3.5-turbo", "gpt-4", "gpt-4o", "Assistant", "Multiagent"]
  chunk_size: 2000

# post-process module config
post_process: 
  check_len_and_split: True
  remove_trans_punctuation: True

# output type that user receive
output_type: 
  subtitle: srt
  video: True
  bilingual: True


