name: Docker Image CI

on:
  push:
    branches: [ "Clips" ]
  pull_request:
    branches: [ "Clips" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
    - name: Build and push Docker image
      run: |
        docker build -f Dockerfile.unified -t willbe03/vidove:latest .
        docker push willbe03/vidove:latest