name: ViDove ci/cd pipeline

on:
    push:
        branches: [ release, main ]
    pull_request:
        branches: [ release, main ]

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        steps:
            - uses: actions/checkout@v4

            - name: Set up python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"
                  architecture: "x64"
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Test with unittest
              run: |
                # python tests/test_*.py
                python tests/test_remove_punc.py
                python tests/test_translation.py

    build:

        runs-on: ubuntu-latest

        needs: test

        steps:

            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Extract metadata (tags, labels) from Docker
              id: meta
              uses: docker/metadata-action@v3
              with:
                  images: 'johojakusha/vidove'

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: |
                      OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

